[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@arbitrum/nitro-contracts/=lib/nitro-contracts/",
    "@bgd-labs/aave-address-book/=lib/aave-address-book/src/",
    "@wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
]
ffi = true

via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
