[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
    "@arbitrum/nitro-contracts/=lib/nitro-contracts/",
    "@bgd-labs/aave-address-book/=lib/aave-address-book/src/",
]
ffi = true

via_ir = true
optimizer_runs = 200

[invariant]
runs = 20
depth = 5
fail_on_revert = true
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[fuzz]
runs = 200
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
